export const locationData = [
  {
    state: 'Abia',
    city: ['Aba', 'Amaeke', 'Arochukwu', 'Ikwuano', 'Ohafia', 'Umuahia', 'Umudike'],
  },
  {
    state: 'Adamawa',
    city: [
      'Gombi',
      'Hong',
      'Mayo belwa',
      'Mubi',
      'Ngurore',
      'Numan',
      'Song',
      'Yola',
      'Yola-central locations',
    ],
  },
  {
    state: 'Akwa ibom',
    city: [
      'Abak',
      'Eket',
      'Etinan',
      'Ikot abassi',
      'Ikot ekpene',
      'Ikot osura',
      'Mkpat enin',
      'Oron',
      'Qua iboh terminal / qit',
      'Uyo',
    ],
  },
  {
    state: 'Anambra',
    city: [
      'Abagana',
      'Achalla / awka',
      'Amawbia / awka',
      'Anambra east lga',
      'Anambra west lga',
      'Awka town',
      'Ayamelum',
      'Dunukofia',
      'Ekwulobia',
      'Ihiala',
      'Nise / awka',
      'Nkpor',
      'Nnewi - alor',
      'Nnewi - awada layout',
      'Nnewi - nnewi',
      'Nnewi - oba',
      'Nnewi - obosi',
      'Nnewi - ojoto',
      'Nnewi - oraifite',
      'Nnewi - oraukwu',
      'Nnewi - ozubulu',
      'Nnewi -nnobi',
      'Nnewi -utuh',
      'Nnewi- abatete',
      'Nnewi- amichi',
      'Nnewi-ichi i',
      'Nnewi-ogidi',
      'Ogbaru',
      'Ogidi / awka',
      'Onitsha',
      'Onitsha-central locations',
      'Onitsha-gra',
      'Oyi',
      'Umuokpe / awka',
    ],
  },
  {
    state: 'Bauchi',
    city: [
      'Alkaleri',
      'Awala',
      'Bauchi central district',
      'Bauchi north district',
      'Bauchi south district',
      'Central market',
      'Darazo',
      'Fadamar mada',
      'Gida dubu',
      'Ibrahim bako',
      'Katagum/azare',
      'New gra / wuntin dada',
      'Old gra',
      'Railway / fed. low cost',
      'Wunti',
      'Yan doka',
      'Yelwa / fed. poly',
    ],
  },
  {
    state: 'Bayelsa',
    city: [
      'Amassoma',
      'Brass',
      'Ekeremor',
      'Kiama',
      'Kolokuma/opokuma',
      'Nembe',
      'Ogbia',
      'Otuoke',
      'Sagbama',
      'Southern ijaw',
      'Wilberforce island',
      'Yenagoa',
    ],
  },
  {
    state: 'Benue',
    city: [
      'Gboko',
      'Katsina-ala',
      'Makurdi-central locations',
      'Markudi-bank road',
      'Markurdi-airforce base',
      'Markurdi-benue state university',
      'Markurdi-high level',
      'Markurdi-judges quaters',
      'Markurdi-low-level',
      'Markurdi-modern market',
      'Markurdi-new gra',
      'Markurdi-nyima',
      'Markurdi-old gra',
      'Markurdi-secretariat',
      'Markurdi-university of agric',
      'Markurdi-wadata',
      'Markurdi-wurukum',
      'Mkar',
      'Otukpo',
      'Vandekya',
      'Yandev',
    ],
  },
  {
    state: 'Borno',
    city: ['Maiduguri', 'Monguno'],
  },
  {
    state: 'Cross river',
    city: [
      'Abi',
      'Akamkpa',
      'Akpabuyo',
      'Bakassi',
      'Bekwarra',
      'Biase',
      'Boki',
      'Calabar',
      'Calabar-municipality',
      'Calabar south',
      'Etung',
      'Ikom',
      'Obanliku',
      'Obubra',
      'Obudu',
      'Odukpani',
      'Ogoja',
      'Yakuur',
      'Yala',
    ],
  },
  {
    state: 'Delta',
    city: [
      'Warri-deco road',
      'Abraka-ajanomi',
      'Abraka-delsu campus 1',
      'Abraka-delsu campus 2',
      'Abraka-delsu campus 3',
      'Abraka-ekrejeta',
      'Abraka-erho',
      'Abraka-fsp/hospital road',
      'Abraka-new road',
      'Abraka-ojeta',
      'Abraka-old sapele agbor road',
      'Abraka-oria',
      'Abraka-oruarivie',
      'Abraka-otorho',
      'Abraka-police station road',
      'Abraka-ughere-urhuagbesa',
      'Abraka-umeghe',
      'Abraka-umono road',
      'Abraka-urhuoka',
      'Abraka-winners road',
      'Agbor - abavo',
      'Agbor - alero',
      'Agbor - alihame',
      'Agbor - boji boji',
      'Agbor - ekuoma',
      'Agbor - igbodo',
      'Agbor - obi',
      'Agbor - owa oyibu',
      'Agbor - umunede',
      'Aladja',
      'Asaba-abraka market',
      'Asaba-achala ibusa',
      'Asaba-akuebulu',
      'Asaba-akuofor',
      'Asaba-anwai',
      'Asaba-asaba airport',
      'Asaba-asaba/benin express road',
      'Asaba-bonsaac',
      'Asaba-cable point',
      'Asaba-camp 74',
      'Asaba-dennis osadebe way',
      'Asaba-dla road',
      'Asaba-ezenei',
      'Asaba-federal college',
      'Asaba-gra core area',
      'Asaba-housing estate',
      'Asaba-ibusa road',
      'Asaba-infant jesus road',
      'Asaba-jarret',
      'Asaba-jesus saves road',
      'Asaba-junic hotel area',
      'Asaba-koka junction',
      'Asaba-nnebisi',
      'Asaba-okpanam',
      'Asaba-okwe',
      'Asaba-summit',
      'Ebrumede',
      'Eku-eku central location',
      'Eku-eku-obiaruku road',
      'Eku-eku-warri road',
      'Fupre',
      'Isele',
      'Kwale-central location',
      'Obiaruku-central location',
      'Obiaruku-novena university',
      'Oghara - nigerian navy base',
      'Oghara - oghara junction',
      'Oghara - ogharefe',
      'Oghara - oghareki',
      'Oghara - ovade',
      'Oghara-otefe',
      'Ogwashi',
      'Oleh-central location',
      'Oleh-delsu oleh campus',
      'Otor',
      'Ovwian',
      'Ozoro-delta state poly',
      'Ozoro-emu obiogo road',
      'Ozoro-ozoro road',
      'Sapele-ajogodo',
      'Sapele-akintola',
      'Sapele-amukpe',
      'Sapele-gana',
      'Sapele-jesse',
      'Sapele-mosogar',
      'Sapele-new road',
      'Sapele-ogorode',
      'Sapele-okpe road',
      'Sapele-ugberikoko',
      'Sapele-yoruba road',
      'Udu-aladja',
      'Udu-ofagbe',
      'Udu-orhuworun',
      'Udu-orhuworun road',
      'Udu-otor',
      'Udu-udu express',
      'Udu-usiefrun',
      'Ughelli ekerejebor road',
      'Ughelli-1st emekpa junction',
      'Ughelli-ekuigbo',
      'Ughelli-general hospital',
      'Ughelli-isoko road',
      'Ughelli-market road',
      'Ughelli-oteri',
      'Ughelli-otovwodo junction',
      'Ughelli-post office',
      'Ughelli-sokaji',
      'Ughelli-uloho avenue',
      'Ughelli-upper afiesere',
      'Umunede',
      'Warri-airport road',
      'Warri-edjeba',
      'Warri-efurun',
      'Warri-ekpan',
      'Warri-enerhen',
      'Warri-gra',
      'Warri-jakpa',
      'Warri-jeddo',
      'Warri-n.p.a',
      'Warri-ogunu',
      'Warri-osubi',
      'Warri-p.t.i',
      'Warri-refinery road',
      'Warri-ubeji',
      'Warri-ugwuangwe',
    ],
  },
  {
    state: 'Ebonyi',
    city: [
      'Abakaliki',
      'Afikpo north',
      'Afikpo south (edda)',
      'Ezza north',
      'Ezza south',
      'Ikwo',
      'Ishielu',
      'Ivo',
      'Izzi',
      'Ohaozara',
      'Ohaukwu',
      'Onicha',
    ],
  },
  {
    state: 'Edo',
    city: [
      'Akoko edo',
      'Benin-adesuwa',
      'Benin-aduwawa',
      'Benin-agbor park',
      'Benin-akpapava',
      'Benin-dumez',
      'Benin-ekae',
      'Benin-ekenwan',
      'Benin-ekhor',
      'Benin-ekosodin',
      'Benin-ekuku',
      'Benin-eriaria',
      'Benin-etete',
      'Benin-evbotube',
      'Benin-ewemade village',
      'Benin-eyaen',
      'Benin-gra',
      'Benin-idogbo',
      'Benin-ihogben',
      'Benin-ikpoba hill',
      'Benin-ikpokan',
      'Benin-iwogban',
      'Benin-limits',
      'Benin-medical road',
      'Benin-new benin market',
      'Benin-npdc',
      'Benin-obe',
      'Benin-ogbelaka',
      'Benin-ohovbeokao',
      'Benin-oko-gba',
      'Benin-ologbo',
      'Benin-oregbeni',
      'Benin-ring road',
      'Benin-secretariat',
      'Benin-st saviour',
      'Benin-ugbekun',
      'Benin-ugbor',
      'Benin-ugbowo',
      'Benin-uhumwuimwu',
      'Benin-urhkwuosa',
      'Benin-urubi',
      'Benin-use',
      'Benin-uselu',
      'Benin-uwelu',
      'Egor-egor',
      'Egor-environ camps',
      'Egor-oviasuyi camp',
      'Ekiadolor',
      'Ekiadoro',
      'Ekpoma- ujoehenlen',
      'Ekpoma-afua',
      'Ekpoma-ambrose ali uni',
      'Ekpoma-debow',
      'Ekpoma-ebhoakhua',
      'Ekpoma-eguare',
      'Ekpoma-emado',
      'Ekpoma-idumebo',
      'Ekpoma-idumegbede',
      'Ekpoma-ihumudumu',
      'Ekpoma-ile',
      'Ekpoma-iruekpen',
      'Ekpoma-okpenu',
      'Ekpoma-oriafor',
      'Ekpoma-ozalla',
      'Ekpoma-palmwell',
      'Ekpoma-ujemen',
      'Esan center',
      'Esan south',
      'Esan west',
      'Etsako central',
      'Etsako east',
      'Etsako igbira camp',
      'Etsako west',
      'Etsako-agenebode',
      'Etsako-aibotse',
      'Etsako-aigiere',
      'Etsako-auchi market',
      'Etsako-auchi poly campus 1',
      'Etsako-auchi poly campus 2',
      'Etsako-auchi poly campus 3',
      'Etsako-azukala',
      'Etsako-fugar junction',
      'Etsako-igbe road',
      'Etsako-iraokhor',
      'Etsako-itsukwi',
      'Etsako-iyekhei',
      'Etsako-jattu junction',
      'Etsako-ogbona',
      'Etsako-okpella',
      'Etsako-south ibie',
      'Etsako-uzanu',
      'Igueben',
      'Ikpoba okha',
      'Okada',
      'Okada-central-location',
      'Okada-estate-gate',
      'Okada-gra',
      'Okada-hostel-gate',
      'Okada-igbinedion',
      'Okada-igbobazuwa',
      'Okada-iyaro',
      'Okada-main-campus',
      'Okada-new-road',
      'Okada-okada-village',
      'Okada-teaching-hospital',
      'Oluku',
      'Orhionmwon',
      'Ovia north east',
      'Ovia south west',
      'Owan east',
      'Owan west',
      'Ubiaja',
      'Ugbowo',
      'Ugbowo- isiohor',
      'Ugbowo-adolor college road',
      'Ugbowo-bdpa',
      'Ugbowo-edpa',
      'Ugbowo-federal road/ osasogie',
      'Ugbowo-oluku',
      'Ugbowo-s/t barracks',
      'Ugbowo-technical college road',
      'Ugbowo-ubth',
      'Ugbowo-uniben',
      'Ugbowo-uselu',
      'Ugbowo-uwagboe',
      'Ugbowo-uwasota',
      'Ugbowo-uwelu',
      'Uhen',
      'Uromi',
    ],
  },
  {
    state: 'Ekiti',
    city: [
      'Ado ekiti',
      'Afebabalola',
      'Aramoko',
      'Efon',
      'Efon-alaaye',
      'Ekiti east',
      'Emure',
      'Gbonyin',
      'Ido osi',
      'Ijero',
      'Ikere',
      'Ikole',
      'Ilawe',
      'Ilejemeje',
      'Irepodun/ifelodun',
      'Ise ekiti',
      'Ise/orun',
      'Iworoko',
      'Moba',
      'Omuo',
      'Otun',
      'Oye',
    ],
  },
  {
    state: 'Enugu',
    city: [
      'Agbani town',
      'Aninri',
      'Aniri',
      'Awgu',
      'Enugu garki',
      'Enugu transekulu',
      'Enugu-abakpa nike',
      'Enugu-central location',
      'Ezeagu',
      'Igbo etiti',
      'Igbo eze north',
      'Igbo eze south',
      'Isi uzo',
      'Ituku ozalla',
      'Nkanu east',
      'Nkanu west',
      'Nsukka',
      'Nsukka - edeoballa',
      'Nsukka - ehaalumona',
      'Oji river',
      'Udenu',
      'Udi',
      'Uzo-uwani',
    ],
  },
  {
    state: 'Federal capital territory',
    city: [
      'Abaji',
      'Abuja airport road- abuja technology village',
      'Abuja airport road- chika',
      'Abuja airport road- gosa / sabon lugbe',
      'Abuja airport road- kuchingoro',
      'Abuja airport road- kyami / centenary city',
      'Abuja airport road- nnamdi azike airport',
      'Abuja airport road- piwoyi',
      'Abuja airport road- pyakasa',
      'Abuja airport road- riverpark /trademore',
      'Abuja airport road- sauka/immigration hq',
      'Abuja- apo central',
      'Abuja- apo legislative zone a',
      'Abuja- apo legislative zone b',
      'Abuja- apo legislative zone c',
      'Abuja- apo legislative zone d',
      'Abuja- apo legislative zone e',
      'Abuja- apo mechanic village',
      'Abuja- apo resettlement zone a',
      'Abuja- apo resettlement zone b',
      'Abuja- apo resettlement zone c',
      'Abuja- apo resettlement zone d',
      'Abuja- apo resettlement zone e',
      'Abuja- durumi',
      'Abuja- durumi phase 2',
      'Abuja- garki area 1',
      'Abuja- garki area 10',
      'Abuja- garki area 11',
      'Abuja- garki area 2',
      'Abuja- garki area 3',
      'Abuja- garki area 7',
      'Abuja- garki area 8',
      'Abuja- gwarinpa 1st avenue',
      'Abuja- gwarinpa 2nd avenue',
      'Abuja- gwarinpa 3rd avenue',
      'Abuja- gwarinpa 4th avenue',
      'Abuja- gwarinpa 5th avenue',
      'Abuja- gwarinpa 6th avenue',
      'Abuja- gwarinpa 7th avenue',
      'Abuja- gwarinpa extension',
      'Abuja- katampe extension',
      'Abuja- katampe main',
      'Abuja- kubwa 2/1 phase 1',
      'Abuja- kubwa 2/2 phase 2',
      'Abuja- kubwa arab road',
      'Abuja- kubwa byazhin',
      'Abuja- kubwa extension 3',
      'Abuja- kubwa gbazango',
      'Abuja- kubwa phase 3',
      'Abuja- kubwa pw',
      'Abuja- kubwa- fcda/fha',
      'Abuja- life camp extension',
      'Abuja- mabushi',
      'Abuja- maitama aleiro',
      'Abuja- maitama aso drive',
      'Abuja- maitama central',
      'Abuja- maitama extension',
      'Abuja-asokoro',
      'Abuja-bwari',
      'Abuja-central',
      'Abuja-dakibiyu',
      'Abuja-dawaki',
      'Abuja-dei-dei',
      'Abuja-dutse',
      'Abuja-efab',
      'Abuja-galadimawa',
      'Abuja-games village',
      'Abuja-garki2',
      'Abuja-gudu',
      'Abuja-guzape',
      'Abuja-gwagwalada',
      'Abuja-jabi',
      'Abuja-jahi',
      'Abuja-kabusa',
      'Abuja-kado',
      'Abuja-karu',
      'Abuja-kaura district',
      'Abuja-kuje',
      'Abuja-life camp',
      'Abuja-lokogoma',
      'Abuja-lugbe across zone1-9',
      'Abuja-lugbe kapwa',
      'Abuja-lugbe mrbiggs',
      'Abuja-lugbe new site',
      'Abuja-lugbe peace village',
      'Abuja-lugbe police sign post',
      'Abuja-lugbe premier academy',
      'Abuja-lugbe sector f',
      'Abuja-lugbe skye bank',
      'Abuja-lugbe total',
      'Abuja-lugbe tudun wada',
      'Abuja-mararaba',
      'Abuja-nyanya',
      'Abuja-prince and princess',
      'Abuja-suncity',
      'Abuja-sunny valle',
      'Abuja-utako',
      'Abuja-wuse zone 1',
      'Abuja-wuse zone 2',
      'Abuja-wuse zone 3',
      'Abuja-wuse zone 4',
      'Abuja-wuse zone 5',
      'Abuja-wuse zone 6',
      'Abuja-wuse zone 7',
      'Abuja-wuse11',
      'Abuja-wuye',
      'Airport road iddo',
      'Airport road kuchingoro / chika / pyakasa',
      'Airport road sauka /trademore / airport',
      'Dutse',
      'Gidan mangoro',
      'Gwagwalada',
      'Idu',
      'Jikowyi',
      'Karimo',
      'Karu',
      'Kubwa central',
      'Kwali',
      'Lugbe',
      'Ministers hill',
      'Mpape',
      'Nicon junction',
      'Tungan maje',
      'Zuba',
    ],
  },
  {
    state: 'Gombe',
    city: [
      'Akko',
      'Arawa',
      'Ashaka',
      'Bajoga',
      'Balanga',
      'Barunde',
      'Bcj',
      'Billiri',
      'Bolari',
      'Bye pass',
      'Dukku',
      'Funakaye',
      'Gombe',
      'Gra',
      'Jekadafari',
      'Kaltungo',
      'Kasuwan mata',
      'Kwami',
      'Malamfidi',
      'Nafada',
      'Nayi nawa',
      'Orji quarters',
      'Pantami',
      'Shongom',
      'State low cost',
      'Tudun wada',
      'Tunfere',
      'Yamaltu/deba',
    ],
  },
  {
    state: 'Imo',
    city: [
      'Amakohia-akwakuma',
      'Ezinihitte',
      'Ihiagwa',
      'Ihiala',
      'Isuochi',
      'Mbaise',
      'Ngor okpala',
      'Nwangele',
      'Obowo',
      'Oguta',
      'Okigwe',
      'Orlu',
      'Owerri-aladinma',
      'Owerri-douglas',
      'Owerri-ihiagwa',
      'Owerri-ikenegbu',
      'Owerri-irete',
      'Owerri-nekede',
      'Owerri-orji',
      'Owerri-portharcourt road',
      'Owerri-umunguma',
      'Owerri-wetheral',
      'Owerri-world bank',
    ],
  },
  {
    state: 'Jigawa',
    city: ['Dutse', 'Gumel', 'Hadeja', 'Hadejia', 'Jahum', 'Jahun', 'Kazaure', 'Ringim'],
  },
  {
    state: 'Kaduna',
    city: [
      'Airport',
      'Angwan sariki',
      'Angwan sariki / malali',
      'Barnawa',
      'Bye pass',
      'Central market',
      'Constitution road',
      'Goni gora',
      'Goni gora / kurumashi',
      'Ibbi',
      'Independence road',
      'Jaji',
      'Kabala',
      'Kachia',
      'Kaduna central',
      'Kafanchan',
      'Kakuri',
      'Kakuri / trikania',
      'Kawo-kaduna',
      'Kikinu',
      'Kurumashi',
      'Low coast',
      'Low cost',
      'Makarfi',
      'Malali',
      'Narayi',
      'Nda',
      'Nncp',
      'Regachuku',
      'Sabo',
      'Sign board',
      'Station roundabout',
      'Trikania',
      'Tundu wada',
      'Zaria',
    ],
  },
  {
    state: 'Kano',
    city: [
      'Airforce base/airport road',
      'Audu bako way',
      'Badarawa',
      'Bichi',
      'Brigade',
      'Buk old site/new site',
      'Court road',
      'Fagge',
      'Farm centre',
      'Gadan kaya',
      'Gadun albasu',
      'Gaya',
      'Goron dutse',
      'Gwammaja',
      'Gyadi-gyadi / zoo road',
      'Gyadi-gyadi/zaria road',
      'Hotoro',
      'Kabuga',
      'Kano - nassarawa',
      'Kano city',
      'Karkasara',
      'Katsina road',
      'Kawo-kano',
      'Murtala mohammed way',
      'Nassarawa gra',
      'No mansland',
      'Panshekara',
      'Sabon gari',
      'Sallari',
      'Sharada',
      'Sharada / gwammaja',
      'Tarauni',
      'Wudil',
      'Yankaba/ hadejia road',
      "Zaria road / na'ibawa",
      'Zoo road',
    ],
  },
  {
    state: 'Kebbi',
    city: ['Ambrusa', 'Argungu', 'Birnin kebbi'],
  },
  {
    state: 'Kogi',
    city: [
      'Abobo',
      'Ajaokuta',
      'Ankpa',
      'Ayangba',
      'Cbn',
      'Felele',
      'Ganaja',
      'Idah',
      'Itakpe',
      'Jingbe',
      'Kabba',
      'Lokoja-central locations',
      'Mammy market',
      'Obajana',
      'Okenne',
      'Zango',
    ],
  },
  {
    state: 'Kwara',
    city: [
      'Asa',
      'Baruten',
      'Edu',
      'Ekiti',
      'Ifelodun',
      'Ilorin - agbooba-adewole estate',
      'Ilorin - challenge-uith',
      'Ilorin - gaaakanbi-asadam-ganmo',
      "Ilorin - surulere-ojooba-emir's",
      'Ilorin - unity-newyidi-stadium',
      'Ilorin -taiwo-airport',
      'Ilorin -tanke-unilorin-pipeline',
      'Ilorin east',
      'Ilorin south',
      'Ilorin west',
      'Ilorin-central',
      'Irepodun',
      'Isin',
      'Kaiama',
      'Moro',
      'Offa',
      'Oke ero',
      'Oyun',
      'Pategi',
    ],
  },
  {
    state: 'Lagos',
    city: [
      'Abule egba (agbado ijaye road)',
      'Abule egba (ajasa command rd)',
      'Abule egba (ajegunle)',
      'Abule egba (alagbado)',
      'Abule egba (alakuko)',
      'Abule egba (ekoro road)',
      'Abule egba (meiran road)',
      'Abule egba (new oko oba)',
      'Abule egba (old otta road)',
      'Agbara',
      'Agege (ajuwon akute road)',
      'Agege (dopemu)',
      'Agege (iju road)',
      'Agege (old abeokuta road)',
      'Agege (old otta road)',
      'Agege (orile agege)',
      'Agiliti',
      'Agungi (lekki)',
      'Ajao estate',
      'Alfa beach',
      'Amuwo',
      'Anthony village',
      'Apapa (ajegunle)',
      'Apapa (amukoko)',
      'Apapa (gra)',
      'Apapa (kiri kiri)',
      'Apapa (olodi)',
      'Apapa (suru alaba)',
      'Apapa (tincan)',
      'Apapa (warf rd)',
      'Awoyaya',
      'Awoyaya-container bustop',
      'Awoyaya-eko akete estate',
      'Awoyaya-eputu',
      'Awoyaya-gbetu iwerekun road',
      'Awoyaya-idowu eletu',
      'Awoyaya-mayfair gardens',
      'Awoyaya-ogunlana busstop',
      'Awoyaya-ologunfe',
      'Awoyaya-oribanwa',
      'Badagry',
      'Berger',
      'Bogije',
      'Coker',
      'Doyin',
      'Ejigbo-ailegun road',
      'Ejigbo-bucknor',
      'Ejigbo-ile epo',
      'Ejigbo-isheri osun',
      'Ejigbo-jakande wood market',
      'Ejigbo-nnpc road',
      'Ejigbo-oke-afa',
      'Ejigbo-pipeline',
      'Ejigbo-powerline',
      'Elemoro',
      'Epe',
      'Fagba (iju road)',
      'Festac (1st avenue)',
      'Festac (2nd avenue)',
      'Festac (3rd avenue)',
      'Festac (4th avenue)',
      'Festac (5th avenue)',
      'Festac (6th avenue)',
      'Festac (7th avenue)',
      'Gbagada- ifako',
      'Gbagada-abule okuta',
      'Gbagada-araromi',
      'Gbagada-deeper life',
      'Gbagada-diya',
      'Gbagada-expressway',
      'Gbagada-hospital',
      'Gbagada-l&k',
      'Gbagada-new garage',
      'Gbagada-olopomeji',
      'Gbagada-pedro',
      'Gbagada-sawmill',
      'Gbagada-sholuyi',
      'Ibeju lekki',
      'Idimu',
      'Igando',
      'Ijanikin',
      'Ijegun ikotun',
      'Ijegun-obadore road',
      'Ijora',
      'Ikeja (adeniyi jones)',
      'Ikeja (alausa)',
      'Ikeja (allen avenue)',
      'Ikeja (computer village)',
      'Ikeja (gra)',
      'Ikeja (m m airport)',
      'Ikeja (mangoro)',
      'Ikeja (oba-akran)',
      'Ikeja (opebi)',
      'Ikorodu (adamo)',
      'Ikorodu (agbede)',
      'Ikorodu (agbowa)',
      'Ikorodu (agric)',
      'Ikorodu (bayeku)',
      'Ikorodu (eyita)',
      'Ikorodu (gberigbe)',
      'Ikorodu (ijede)',
      'Ikorodu (imota)',
      'Ikorodu (ita oluwo)',
      'Ikorodu (itamaga)',
      'Ikorodu (offin)',
      'Ikorodu (owode-ibese)',
      'Ikorodu road-ajegunle',
      'Ikorodu road-irawo',
      'Ikorodu road-owode onirin',
      'Ikorodu(elepe)',
      'Ikorodu(laspotech)',
      'Ikorodu(ogolonto)',
      'Ikorodu(sabo)',
      'Ikorodu- imota caleb university',
      'Ikorodu-agufoye',
      'Ikorodu-benson',
      'Ikorodu-garage',
      'Ikorodu-odokekere',
      'Ikorodu-odonla',
      'Ikorodu-ogijo',
      'Ikota',
      'Ikotun',
      'Ikoyi (awolowo road)',
      'Ikoyi (bourdillon)',
      'Ikoyi (dolphin)',
      'Ikoyi (glover road)',
      'Ikoyi (keffi)',
      'Ikoyi (kings way road)',
      'Ikoyi (obalende)',
      'Ikoyi (queens drive)',
      'Ikoyi mtn ( pickup station)',
      'Ilaje (bariga)',
      'Ilupeju (lagos)',
      'Isheri ikotun',
      'Isheri magodo',
      'Isolo',
      'Iyana ejigbo',
      'Iyana iba',
      'Iyana ipaja (abesan)',
      'Iyana ipaja (aboru)',
      'Iyana ipaja (ayobo road)',
      'Iyana ipaja (command road)',
      'Iyana ipaja (egbeda)',
      'Iyana ipaja (ikola road)',
      'Iyana ipaja (iyana ipaja road)',
      'Iyana ipaja (shasha)',
      'Jakande (lekki)',
      'Jankande (isolo)',
      'Jumia-experience-center',
      'Ketu- agboyi',
      'Ketu-alapere',
      'Ketu-cmd road',
      'Ketu-demurin',
      'Ketu-ikosi road',
      'Ketu-ile ile',
      'Ketu-iyana school',
      'Ketu-tipper garage',
      'Lagos island (adeniji)',
      'Lagos island (marina)',
      'Lagos island (onikan)',
      'Lagos island (sura)',
      'Lagos island (tbs)',
      'Lakowe',
      'Lakowe-adeba road',
      'Lakowe-golf',
      'Lakowe-kajola',
      'Lakowe-school gate',
      'Lekki -vgc',
      'Lekki 1 (bishop durosimi)',
      'Lekki 1 (f.t kuboye street)',
      'Lekki 1 (omorinre johnson)',
      'Lekki phase 1 (admiralty road)',
      'Lekki phase 1 (admiralty way)',
      'Lekki phase 1 (fola osibo)',
      'Lekki-agungi',
      'Lekki-ajah (abijo)',
      'Lekki-ajah (addo road)',
      'Lekki-ajah (badore)',
      'Lekki-ajah (ilaje)',
      'Lekki-ajah (ilasan)',
      'Lekki-ajah (jakande)',
      'Lekki-ajah (sangotedo)',
      'Lekki-awoyaya',
      'Lekki-chisco',
      'Lekki-elf',
      'Lekki-igboefon',
      'Lekki-ikate elegushi',
      'Lekki-jakande (kazeem eletu)',
      'Lekki-maruwa',
      'Lekki-oniru estate',
      'Lekki-osapa london',
      'Magboro',
      'Magodo',
      'Maryland (mende)',
      'Maryland (onigbongbo)',
      'Mebanmu',
      'Mile 12',
      'Mile 12 -ajelogo',
      'Mile 12-agboyi ketu',
      'Mile 12-doyin omololu',
      'Mile 12-orishigun',
      'Mile 2',
      'Mushin -palm avenue',
      'Mushin-agege motor road',
      'Mushin-daleko market',
      'Mushin-fatai atere',
      'Mushin-idi oro',
      'Mushin-idi-araba',
      'Mushin-ilasamaja road',
      'Mushin-isolo road',
      'Mushin-ladipo road',
      'Mushin-mushin market',
      'Mushin-olateju',
      'Mushin-papa ajao',
      'Odongunyan',
      'Ogba- akilo road',
      'Ogba- college road',
      'Ogba- lateef jakande road',
      'Ogba-acme road',
      'Ogba-aguda',
      'Ogba-county',
      'Ogba-ifako-idiagbon',
      'Ogba-ifako-orimolade',
      'Ogba-isheri road',
      'Ogba-obawole',
      'Ogba-ojodu',
      'Ogba-oke ira',
      'Ogba-oke ira 2nd juction',
      'Ogba-surulere ind rd',
      'Ogba-wemco road',
      'Ogudu',
      'Ojo',
      'Ojo shibiri',
      'Ojo-abule oshun',
      'Ojo-adaloko',
      'Ojo-agric',
      'Ojo-ajangbadi',
      'Ojo-alaba international',
      'Ojo-alaba rago',
      'Ojo-alaba suru',
      'Ojo-alakija',
      'Ojo-cassidy',
      'Ojo-ijegun',
      'Ojo-ilogbo',
      'Ojo-ojo barracks',
      'Ojo-okokomaiko',
      'Ojo-old ojo road',
      'Ojo-onireke',
      'Ojo-ppl',
      'Ojo-shibiri',
      'Ojo-tedi town',
      'Ojo-trade fair',
      'Ojo-volks',
      'Ojodu',
      'Ojokoro',
      'Ojota',
      'Okokomaiko',
      'Okota',
      'Omole phase 1',
      'Omole phase 2',
      'Oregun',
      'Oreyo- igbe',
      'Orile',
      'Osapa (lekki)',
      'Oshodi-bolade',
      'Oshodi-isolo',
      'Oshodi-mafoluku',
      'Oshodi-orile',
      'Oshodi-shogunle',
      'Palmgrove-onipanu',
      'Sari-iganmu',
      'Satelite-town',
      'Somolu',
      'Surulere (adeniran ogunsanya)',
      'Surulere (aguda)',
      'Surulere (bode thomas)',
      'Surulere (fatia shitta)',
      'Surulere (idi araba)',
      'Surulere (ijesha)',
      'Surulere (iponri)',
      'Surulere (itire)',
      'Surulere (lawanson)',
      'Surulere (masha)',
      'Surulere (ogunlana drive)',
      'Surulere (ojuelegba)',
      'Vi (adetokunbo ademola)',
      'Vi (ahmed bello way)',
      'Vi (bishop aboyade cole)',
      'Vi(ajose adeogun)',
      'Vi(akin adeshola)',
      'Vi(bishop oluwale)',
      'Vi(yusuf abiodun)',
      'Victoria island (adeola odeku)',
      'Victoria island (kofo abayomi)',
      'Yaba- abule ijesha',
      'Yaba- fadeyi',
      'Yaba-(sabo)',
      'Yaba-(unilag)',
      'Yaba-abule oja',
      'Yaba-adekunle',
      'Yaba-akoka',
      'Yaba-alagomeju',
      'Yaba-college of education',
      'Yaba-commercial avenue',
      'Yaba-folagoro',
      'Yaba-herbert macaulay way',
      'Yaba-jibowu',
      'Yaba-makoko',
      'Yaba-murtala muhammed way',
      'Yaba-onike iwaya',
      'Yaba-oyingbo',
      'Yaba-tejuosho',
      'Yaba-university road',
      'Yaba-yabatech',
    ],
  },
  {
    state: 'Nasarawa',
    city: [
      'Akwanga',
      'Awe',
      'Doma',
      'Karu',
      'Keana',
      'Keffi',
      'Lafia-bukan sidi',
      'Lafia-central locations',
      'Lafia-college/polytechnic',
      'Lafia-east',
      'Lafia-jos road',
      'Lafia-low cost',
      'Lafia-sabon pegi',
      'Lafia-shabu',
      'Lafia-tudun gwandara',
      'Masaka',
      'Nasarawa',
      'Nasarawa egon',
      'New karu',
      'Obi',
      'Toto',
      'Wamba',
    ],
  },
  {
    state: 'Niger',
    city: [
      'Agai',
      'Baddegi',
      'Bida',
      'Kontagora',
      'Lapai',
      'Madala',
      'Minna-bosso',
      'Minna-central',
      'Minna-chanchaga',
      'Minna-david mark way',
      'Minna-dutsen kura',
      'Minna-easter byepass',
      'Minna-f layout',
      'Minna-fadipe',
      'Minna-farm center',
      'Minna-gidan kwano',
      'Minna-gra',
      'Minna-kpakungu',
      'Minna-kure market',
      'Minna-kuta road',
      'Minna-london street',
      'Minna-m.i wushishi',
      'Minna-maikunkele',
      'Minna-maitumbi',
      'Minna-mandela',
      'Minna-mobil',
      'Minna-okada way',
      'Minna-sango',
      'Minna-sauka ka huta',
      'Minna-shiroro way',
      'Minna-tunga',
      'Minna-western byepass',
      'Suleja',
      'Suleja-guraka',
      'Suleja-kwamba',
      'Suleja-kwankashe',
      'Suleja-maje',
      'Suleja-rafinsanyi',
      'Zuba',
    ],
  },
  {
    state: 'Ogun',
    city: [
      'Abeokuta-adigbe',
      'Abeokuta-central',
      'Abeokuta-elega',
      'Abeokuta-idi aba',
      'Abeokuta-lafenwa',
      'Abeokuta-mko abiola way',
      'Abeokuta-oke mosan',
      'Agbara (opic)',
      'Agbara estate (ogun)',
      'Ago iwoye',
      'Akute',
      'Ewekoro',
      'Ifo',
      'Igbesa (crawford university)',
      'Igbesa (igbesa polytechnic)',
      'Igbesa (lusada)',
      'Ijebu ife',
      'Ijebu igbo',
      'Ijebu north east',
      'Ijebu ode awujaale st',
      'Ijebu ode folagbade',
      'Ijebu ode molipa',
      'Ijebu ode-asiru',
      'Ijebu ode-bonajo',
      'Ijebu ode-degun',
      'Ijebu ode-ibadan road',
      'Ijebu ode-igbeba road',
      'Ijebu ode-italapo',
      'Ijebu ode-new road',
      'Ijebu ode-olisa st',
      'Ijebu ode-osinubi',
      'Ijebu ode-sabo',
      'Ijebu ode-saka',
      'Ijebu ode-tuaboat road',
      'Ijebuode-lekuti',
      'Ikenne',
      'Ilaro-ajilete',
      'Ilaro-ibese',
      'Ilaro-ikosi',
      'Ilaro-leslei road',
      'Ilaro-oke ela',
      'Ilaro-oke odan',
      'Ilaro-orita',
      'Ilaro-papa lanto',
      'Ilishan remo-babcock',
      'Imeko afon',
      'Itele (ijebu)',
      'Mowe ibafo',
      'Oba',
      'Obafemi owode',
      'Obantoko',
      'Odeda',
      'Odogbolu',
      'Ogijo',
      'Ogun-sagamu-remo',
      'Oru',
      'Otta town (akeja navy)',
      'Otta town (bells)',
      'Otta town (convenant)',
      'Otta town (ifo)',
      'Otta town (obansanjo)',
      'Otta town (osi olosun)',
      'Otta town (owode)',
      'Redeemed camp',
      'Remo north',
      'Sango (ijoko)',
      'Sango otta (atan)',
      'Sango otta (iju)',
      'Sango otta (oju ore)',
      'Sango otta (sango)',
      'Sango-otta (toll gate)',
      'Yewa north/south',
    ],
  },
  {
    state: 'Ondo',
    city: [
      'Akoko',
      'Akure oshile',
      'Akure-alagbaka',
      'Akure-futa',
      'Akure-idanre road',
      'Akure-igbatoro',
      'Akure-ijapo estate',
      'Akure-ijare',
      'Akure-ijoka',
      'Akure-ilara mokin',
      'Akure-ilesha garage',
      'Akure-oba adesida',
      'Akure-oba ile',
      'Akure-oda road',
      'Akure-oluwatuyi',
      'Akure-ondo road',
      'Akure-oyemekun road',
      'Akure-shagari village',
      'Ese odo',
      'Idanre',
      'Ifedore',
      'Igbokoda',
      'Illaje',
      'Irele',
      'Odigbo',
      'Okitipipa',
      'Ondo town- sagun',
      'Ondo town- yaba',
      'Ondo town-ajegunle',
      'Ondo town-ajemulegun',
      'Ondo town-mimiko estate',
      'Ondo town-oka',
      'Ondo-akungba',
      'Ondotown-akinjagular',
      'Ondotown-ayeyemi',
      'Ore',
      'Ose',
      'Owo',
    ],
  },
  {
    state: 'Osun',
    city: [
      'Arakeji',
      'Ede',
      'Ejigbo',
      'Ejigbo (osun)',
      'Esaoke',
      'Ijebu',
      'Ijebu-jesa',
      'Ikire',
      'Ikirun',
      'Ila',
      'Ila-orangun',
      'Ile ife',
      'Ile-ife - adesanmi',
      'Ile-ife - ajebamidele',
      'Ile-ife - akarabata',
      'Ile-ife - ap',
      'Ile-ife - aserifa',
      'Ile-ife - awoyeku',
      'Ile-ife - ede road',
      'Ile-ife - eleyele',
      'Ile-ife - ilesa garage/oauth',
      'Ile-ife - iremo',
      'Ile-ife - mayfair',
      'Ile-ife - modomo',
      'Ile-ife - mokuro',
      'Ile-ife - moro/edunabon/ipetumodu',
      'Ile-ife - nta',
      'Ile-ife - oau community',
      'Ile-ife - oduduwa university',
      'Ile-ife - oke d.o',
      'Ile-ife - omole',
      'Ile-ife - opa',
      'Ile-ife - our ladies modakeke',
      'Ile-ife - parakin',
      'Ile-ife - post office/sabo',
      'Ileife-lagere',
      'Ilesha',
      'Iloko',
      'Iree',
      'Iwo',
      'Iwo (osun)',
      'Moro/edunabon/ipetumodu',
      'Oau community',
      'Okuku',
      'Oshogbo',
      'Oshogbo-central locations',
      'Osogbo',
      'Osogbo - agunbelewo',
      'Osogbo - dada estate',
      'Osogbo - igbona',
      'Osogbo - kobo',
      'Osogbo - ofatedo',
      'Osogbo - ogo-oluwa',
      'Osogbo - oke-baale',
      'Osogbo - oke-fia',
      'Osogbo - orisunmibare',
      'Osogbo - ota-efun',
      'Osogbo - powerline',
      'Osogbo - ring road',
    ],
  },
  {
    state: 'Oyo',
    city: [
      'Afijio',
      'Akinyele',
      'Alomoja',
      'Atiba',
      'Atisbo',
      'Egbeda (oyo)',
      'Eruwa',
      'Ibadan-agodi',
      'Ibadan-ajibode',
      'Ibadan-akobo',
      'Ibadan-alakia',
      'Ibadan-apata',
      'Ibadan-bodija',
      'Ibadan-challenge',
      'Ibadan-dugbe',
      'Ibadan-elebu',
      'Ibadan-eleyele',
      'Ibadan-idi ape-ashi',
      'Ibadan-iwo road',
      'Ibadan-jericho',
      'Ibadan-lalupon',
      'Ibadan-molete',
      'Ibadan-monantan',
      'Ibadan-moniya',
      'Ibadan-north west',
      'Ibadan-odo ona',
      'Ibadan-ojoo',
      'Ibadan-olodo',
      'Ibadan-olohunda',
      'Ibadan-olorunsogo',
      'Ibadan-oluyole',
      'Ibadan-ring road',
      'Ibadan-soka',
      'Ibadan-tose',
      'Ibadan-ui',
      'Ibarapa',
      'Idi iroko',
      'Ido',
      'Igbo oloyin',
      'Irepo',
      'Isebo',
      'Iseyin',
      'Itesiwaju',
      'Iwajowa',
      'Iwo (oyo)',
      'Iwo road-olorunsogo',
      'Kajola',
      'Lagelu',
      'Lalupon',
      'Lanlate',
      'Moniya',
      'Ogbomosho',
      'Ogo oluwa',
      'Ologun-eru',
      'Olorunsogo',
      'Ona ara',
      'Orelope',
      'Ori ire',
      'Oyo town-agodongbo',
      'Oyo town-akinmorin',
      'Oyo town-araromi',
      'Oyo town-fola tyre',
      'Oyo town-isokun',
      'Oyo town-jobele',
      'Oyo town-mabolaje',
      'Oyo town-new cele',
      'Oyo town-oroki',
      'Oyo-saki',
      'Sagbe',
      'Surulere',
    ],
  },
  {
    state: 'Plateau',
    city: [
      'Ahmadu bello way',
      'Barikin ladi',
      'Barkin ladi',
      'Bauchi road',
      'Bukuru',
      'Dadin kowa',
      'Farin gada',
      'Haipang',
      'Jos south',
      'Katako',
      'Kuru',
      'Lamingo',
      'Mangu',
      'Nasarawa',
      'Old airport road',
      'Plateau - nasarawa',
      'Plateau- zaria road',
      'Plateau-murtala mohammed way',
      'Rayfield',
      'Rayfield / dadin kowa',
      'Rukuba road',
      'Secretariat junction',
      'Tina junction',
      'Vom',
      'Zaria road',
      'Zarmaganda',
      'Zawan',
      'Zawan / bukuru',
    ],
  },
  {
    state: 'Rivers',
    city: [
      'Abhonema',
      'Ahoada',
      'Airport road - port harcourt',
      'Bonny island',
      'Elele',
      'Elelewon',
      'Eleme-agbonchia',
      'Eleme-akpajo',
      'Eleme-alesa',
      'Eleme-aleto',
      'Eleme-alode',
      'Eleme-ebubu',
      'Eleme-ekporo',
      'Eleme-eteo',
      'Eleme-nchia',
      'Eleme-odido',
      'Eleme-ogale',
      'Eleme-onne',
      'Emouha',
      'Etche',
      'Isiokpo',
      'Okrika',
      'Okrika-okrika town(kirike)',
      'Omoku',
      'Oyigbo-afam',
      'Oyigbo-egberu',
      'Oyigbo-izuoma',
      'Oyigbo-komkom',
      'Oyigbo-mirinwanyi',
      'Oyigbo-ndoki',
      'Oyigbo-obeama',
      'Oyigbo-umuagbai',
      'Phc-new gra -phase 1 2 3 4',
      'Phc-river state university',
      'Phc-woji central location',
      'Portharcourt-abonnema town',
      'Portharcourt-abonnema wharf',
      'Portharcourt-abuloma',
      'Portharcourt-ada george',
      'Portharcourt-agip',
      'Portharcourt-airforce base',
      'Portharcourt-akpajo',
      'Portharcourt-alakahia-upth',
      'Portharcourt-aluu',
      'Portharcourt-amadi ama',
      'Portharcourt-aya-ogologo',
      'Portharcourt-azubie',
      'Portharcourt-bori camp',
      'Portharcourt-borokiri',
      'Portharcourt-choba',
      'Portharcourt-choba-uniport',
      'Portharcourt-churchhill',
      'Portharcourt-d/line',
      'Portharcourt-darick polo',
      'Portharcourt-diobu',
      'Portharcourt-eagle island',
      'Portharcourt-egbelu',
      'Portharcourt-elekahia',
      'Portharcourt-elelewon',
      'Portharcourt-elibolo',
      'Portharcourt-eligbam',
      'Portharcourt-elimgbu',
      'Portharcourt-elinparawon',
      'Portharcourt-eliohani',
      'Portharcourt-eliozu',
      'Portharcourt-eneka',
      'Portharcourt-igwuruta',
      'Portharcourt-intels km 16',
      'Portharcourt-mgbuoba',
      'Portharcourt-mile 1',
      'Portharcourt-mile 2',
      'Portharcourt-mile 3',
      'Portharcourt-mile 4',
      'Portharcourt-mile 5',
      'Portharcourt-mugbuosimini',
      'Portharcourt-new gra-tombia',
      'Portharcourt-nkpogu',
      'Portharcourt-nkpolu',
      'Portharcourt-ogbatai',
      'Portharcourt-ogbogoro',
      'Portharcourt-ogbunabali',
      'Portharcourt-oginigba',
      'Portharcourt-okporo road',
      'Portharcourt-okuru',
      'Portharcourt-old gra',
      'Portharcourt-orazi',
      'Portharcourt-ozuboko',
      'Portharcourt-peter odilli road',
      'Portharcourt-reclamation',
      'Portharcourt-rukpokwu',
      'Portharcourt-rumeme',
      'Portharcourt-rumuaghaolu',
      'Portharcourt-rumuakpakolosi',
      'Portharcourt-rumuepirikom',
      'Portharcourt-rumuevolu',
      'Portharcourt-rumuibekwe',
      'Portharcourt-rumuigbo',
      'Portharcourt-rumukalagbor',
      'Portharcourt-rumukrushi',
      'Portharcourt-rumumasi',
      'Portharcourt-rumuodumaya',
      'Portharcourt-rumuogba',
      'Portharcourt-rumuoke',
      'Portharcourt-rumuokoro',
      'Portharcourt-rumuokwuta',
      'Portharcourt-rumuola',
      'Portharcourt-rumuolumeni',
      'Portharcourt-rumuorosi',
      'Portharcourt-rumuowah',
      'Portharcourt-stadium road',
      'Portharcourt-town',
      'Portharcourt-trans amadi',
      'Portharcourt-woji illom',
      'Portharcourt-woji road',
      'Portharcourt-woji ykc',
      'Portharcourt-woji-elijiji',
      'Rumuagholu',
      'Rumuoduomaya',
    ],
  },
  {
    state: 'Sokoto',
    city: [
      'Sokoto town',
      'Sokoto town-central locations',
      'Sokoto-central location',
      'Sokoto/gusau',
    ],
  },
  {
    state: 'Yobe',
    city: ['Bade', 'Fika', 'Gashua', 'Geidam', 'Nguru'],
  },
];
